version: '3.7'
services:
  pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./cli:/app/cli
    tty: true
    stdin_open: true
    entrypoint: sh